/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioUkMedsRouteImport } from './routes/portfolio.uk-meds'
import { Route as PortfolioRecommendedActionsRouteImport } from './routes/portfolio.recommended-actions'
import { Route as PortfolioOverwatchMonitoringRouteImport } from './routes/portfolio.overwatch-monitoring'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioUkMedsRoute = PortfolioUkMedsRouteImport.update({
  id: '/portfolio/uk-meds',
  path: '/portfolio/uk-meds',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRecommendedActionsRoute =
  PortfolioRecommendedActionsRouteImport.update({
    id: '/portfolio/recommended-actions',
    path: '/portfolio/recommended-actions',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioOverwatchMonitoringRoute =
  PortfolioOverwatchMonitoringRouteImport.update({
    id: '/portfolio/overwatch-monitoring',
    path: '/portfolio/overwatch-monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/overwatch-monitoring': typeof PortfolioOverwatchMonitoringRoute
  '/portfolio/recommended-actions': typeof PortfolioRecommendedActionsRoute
  '/portfolio/uk-meds': typeof PortfolioUkMedsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/overwatch-monitoring': typeof PortfolioOverwatchMonitoringRoute
  '/portfolio/recommended-actions': typeof PortfolioRecommendedActionsRoute
  '/portfolio/uk-meds': typeof PortfolioUkMedsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/overwatch-monitoring': typeof PortfolioOverwatchMonitoringRoute
  '/portfolio/recommended-actions': typeof PortfolioRecommendedActionsRoute
  '/portfolio/uk-meds': typeof PortfolioUkMedsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/portfolio/overwatch-monitoring'
    | '/portfolio/recommended-actions'
    | '/portfolio/uk-meds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/portfolio/overwatch-monitoring'
    | '/portfolio/recommended-actions'
    | '/portfolio/uk-meds'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/portfolio/overwatch-monitoring'
    | '/portfolio/recommended-actions'
    | '/portfolio/uk-meds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioOverwatchMonitoringRoute: typeof PortfolioOverwatchMonitoringRoute
  PortfolioRecommendedActionsRoute: typeof PortfolioRecommendedActionsRoute
  PortfolioUkMedsRoute: typeof PortfolioUkMedsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/uk-meds': {
      id: '/portfolio/uk-meds'
      path: '/portfolio/uk-meds'
      fullPath: '/portfolio/uk-meds'
      preLoaderRoute: typeof PortfolioUkMedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/recommended-actions': {
      id: '/portfolio/recommended-actions'
      path: '/portfolio/recommended-actions'
      fullPath: '/portfolio/recommended-actions'
      preLoaderRoute: typeof PortfolioRecommendedActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/overwatch-monitoring': {
      id: '/portfolio/overwatch-monitoring'
      path: '/portfolio/overwatch-monitoring'
      fullPath: '/portfolio/overwatch-monitoring'
      preLoaderRoute: typeof PortfolioOverwatchMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioOverwatchMonitoringRoute: PortfolioOverwatchMonitoringRoute,
  PortfolioRecommendedActionsRoute: PortfolioRecommendedActionsRoute,
  PortfolioUkMedsRoute: PortfolioUkMedsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
